apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE-deployment
  labels:
    version: v1
    app: $SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $SERVICE
  template:
    metadata:
      labels:
        app: $SERVICE
    spec:
      containers:
        - image: joaollr/$SERVICE:$VERSION
          imagePullPolicy: Always
          name: $SERVICE
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: $SERVICE-secret
            - configMapRef:
                name: core-config
          resources: 
            # requests:
            #   memory: "200Mi"
            #   cpu: "100m" 
            limits:
              memory: "4Gi"  
              cpu: "4000m" 
          volumeMounts:
          - mountPath: /project
            name: $SERVICE-pvc
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: $SERVICE-pvc
          persistentVolumeClaim:
            claimName: $SERVICE-pvc
