apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE-deployment
  labels:
    version: v1
    app: $SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $SERVICE
  template:
    metadata:
      labels:
        app: $SERVICE
    spec:
      containers:
        - image: joaollr/$SERVICE:$VERSION
          imagePullPolicy: Always
          name: $SERVICE
          ports:
            - containerPort: 80
            - containerPort: 8002
            - containerPort: 8080
          resources:
            # requests:
            #   memory: "64Mi"
            #   cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
      imagePullSecrets:
        - name: regcred
        