apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE-deployment
  labels:
    version: v1
    app: $SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $SERVICE
  template:
    metadata:
      labels:
        app: $SERVICE
    spec:
      containers:
        - image: joaollr/$SERVICE:$VERSION
          imagePullPolicy: Always
          name: $SERVICE
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: $SERVICE-secret
            - configMapRef:
                name: core-config
      imagePullSecrets:
        - name: regcred
