apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE-deployment
  labels:
    version: v1
    app: $SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $SERVICE
  template:
    metadata:
      labels:
        app: $SERVICE
    spec:
      containers:
        - image: joaollr/$SERVICE:$VERSION
          imagePullPolicy: Always
          name: $SERVICE
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: monetize-secret
            - configMapRef:
                name: monetize-config
          volumeMounts:
            - mountPath: /app/data
              name: $SERVICE-pvc
          resources: 
            requests:
              memory: "1Gi"
              cpu: "1" 
            limits:
              memory: "2Gi"  
              cpu: "2"    
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: $SERVICE-pvc
          persistentVolumeClaim:
            claimName: $SERVICE-pvc
