apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE-deployment
  labels:
    version: v1
    app: $SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $SERVICE
  template:
    metadata:
      labels:
        app: $SERVICE
    spec:
      containers:
        - image: joaollr/$SERVICE:$VERSION
          imagePullPolicy: Always
          name: $SERVICE
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: $SERVICE-secret
            - configMapRef:
                name: core-config
          volumeMounts:
            - mountPath: /$SERVICE
              name: $SERVICE-pvc
            - mountPath: /default
              name: default-pvc
              #   - mountPath: /app/log
              #     name: $SERVICE
              #   - mountPath: /build/app
              #     name: $SERVICE
              #     # resources: 
              #     #   requests:
              #     #     memory: "512Mi"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "4000m"     
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: $SERVICE-pvc
          persistentVolumeClaim:
            claimName: $SERVICE-pvc
        - name: default-pvc
          persistentVolumeClaim:
            claimName: default-pvc
