apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwtprovider
  labels:
    version: v1
    app: jwtprovider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwtprovider
  template:
    metadata:
      labels:
        app: jwtprovider
    spec:
      containers:
        - image: joaollr/jwtprovider:dev
          imagePullPolicy: Always
          name: jwtprovider
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: jwtprovider-secret
            - configMapRef:
                name: core-config
      imagePullSecrets:
        - name: regcred
